### PR TITLE
Push symbols packages to a separate symbols feed 

### LINKED ISSUE #1884: runtime.RID.Microsoft.NETCore.App packages contain all the symbols
## Steps to reproduce
Look at the latest package on https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.opensuse.42.1-x64.Microsoft.NETCore.App

## Expected  behavior
It should be a reasonable size.

## Actual behavior
It is 90MB, since it contains all the symbol files.

/cc @ericstj @gkhanna79 @chcosta

### PR DESCRIPTION
**Pull request by chcosta**
Fixes #1884 

Core-Setup is now producing symbols packages.  When the standard / symbols packages are uploaded to myget, it's the symbols packages that are getting listed on the main feed.  Prevent this by pushing standard and symbols packages to separate feeds.  

I don't have a good way to test the publishing piece of this outside of official builds. :/

### CODE REVIEW

File: build_projects/dotnet-host-build/NugetUtil.cs [hunk 1]
```diff
@@ -8,25 +9,25 @@ namespace Microsoft.DotNet.Cli.Build
...
             string packageDirPath,
             string destinationUrl,
             string apiKey,
-            bool includeSymbolPackages)
+            NuGetIncludePackageType includePackageTypes)
         {
-            string[] paths;
-            if (includeSymbolPackages)
+            List<string> paths = new List<string>();
+            if ((includePackageTypes & NuGetIncludePackageType.Standard) != 0)
```
Comment (dagood) [inline build_projects/dotnet-host-build/NugetUtil.cs]: `HasFlag`?

File: build_projects/dotnet-host-build/NugetUtil.cs [hunk 2]
```diff
@@ -8,25 +9,25 @@ namespace Microsoft.DotNet.Cli.Build
 {
     public static class NuGetUtil
     {
+        public enum NuGetIncludePackageType
+        {
+            Standard = 1,
+            Symbols
```
Comment (dagood) [inline build_projects/dotnet-host-build/NugetUtil.cs]: I think it's standard to specify each value when making flags (and marking `[Flags]`), since beyond `2` this doesn't work.

File: build_projects/dotnet-host-build/PublishTargets.cs [hunk 3]
```diff
@@ -63,9 +63,15 @@ public static BuildTargetResult Publish(BuildTargetContext c)
...
-            string nugetFeedUrl = EnvVars.EnsureVariable("CLI_NUGET_FEED_URL");
             string apiKey = EnvVars.EnsureVariable("CLI_NUGET_API_KEY");
-            NuGetUtil.PushPackages(Dirs.Packages, nugetFeedUrl, apiKey, IncludeSymbolPackages);
+
+            string nugetFeedUrl = EnvVars.EnsureVariable("CLI_NUGET_FEED_URL");
+            NuGetUtil.PushPackages(Dirs.Packages, nugetFeedUrl, apiKey, NuGetUtil.NuGetIncludePackageType.Standard);
+            if(IncludeSymbolPackages)
+            {
+                string symbolsNugetFeedUrl = EnvVars.EnsureVariable("CLI_NUGET_SYMBOLS_FEED_URL");
+                NuGetUtil.PushPackages(Dirs.PackagesNoRID, symbolsNugetFeedUrl, apiKey, NuGetUtil.NuGetIncludePackageType.Symbols);
```
Comment (dagood) [inline build_projects/dotnet-host-build/PublishTargets.cs]: Why `PackagesNoRID` here rather than `Packages`?

File: build_projects/dotnet-host-build/PublishTargets.cs [hunk 4]
```diff
@@ -63,9 +63,15 @@ public static BuildTargetResult Publish(BuildTargetContext c)
         [BuildArchitectures(BuildArchitecture.x64)]
         public static BuildTargetResult PublishDotnetDebToolPackage(BuildTargetContext c)
         {
-            string nugetFeedUrl = EnvVars.EnsureVariable("CLI_NUGET_FEED_URL");
             string apiKey = EnvVars.EnsureVariable("CLI_NUGET_API_KEY");
-            NuGetUtil.PushPackages(Dirs.Packages, nugetFeedUrl, apiKey, IncludeSymbolPackages);
+
+            string nugetFeedUrl = EnvVars.EnsureVariable("CLI_NUGET_FEED_URL");
+            NuGetUtil.PushPackages(Dirs.Packages, nugetFeedUrl, apiKey, NuGetUtil.NuGetIncludePackageType.Standard);
+            if(IncludeSymbolPackages)
```
Comment (dagood) [inline build_projects/dotnet-host-build/PublishTargets.cs]: \<nit> Missing space after `if`

File: buildpipeline/Core-Setup-Signing-Windows-x64.json [hunk 5]
```diff
@@ -197,6 +177,26 @@
     },
     {
       "enabled": true,
+      "continueOnError": true,
+      "alwaysRun": false,
+      "displayName": "PackagePkgProjects",
```
Comment (dagood) [inline buildpipeline/Core-Setup-Signing-Windows-x64.json]: Why is this moved?

File: build_projects/dotnet-host-build/PublishTargets.cs (hunk 3 above)
Comment (chcosta) [inline build_projects/dotnet-host-build/PublishTargets.cs]: copy-paste error, thanks

File: build_projects/dotnet-host-build/NugetUtil.cs (hunk 1 above)
Comment (chcosta) [inline build_projects/dotnet-host-build/NugetUtil.cs]: Nice, I didn't know about that method

File: buildpipeline/Core-Setup-Signing-Windows-x64.json (hunk 5 above)
Comment (chcosta) [inline buildpipeline/Core-Setup-Signing-Windows-x64.json]: no idea, i'll move it back.

File: build_projects/dotnet-host-build/NugetUtil.cs [hunk 6]
```diff
@@ -8,25 +9,26 @@ namespace Microsoft.DotNet.Cli.Build
...
             string packageDirPath,
             string destinationUrl,
             string apiKey,
-            bool includeSymbolPackages)
+            NuGetIncludePackageType includePackageTypes)
         {
-            string[] paths;
-            if (includeSymbolPackages)
+            List<string> paths = new List<string>();
+            if ((includePackageTypes.HasFlag(NuGetIncludePackageType.Standard)))
```
Comment (dagood) [inline build_projects/dotnet-host-build/NugetUtil.cs]: Redundant wrapping `()`

Comment (chcosta) [inline build_projects/dotnet-host-build/NugetUtil.cs]: well that's silly

**Comment by chcosta** [comment]
The move to buildtools should get us closer to using a common infrastructure.  I'm building up quite the library of core-setup "tasks" with that conversion work that I need to refactor and can *mostly* move to buildtools.  I'm certainly not a fan of how core-setup handles publishing and its use of environment variables, but I'm not certain how much of that cleanup work I'll be able to tackle with the initial conversion.
