### PR TITLE
Fail early on duplicate runtime properties

### LINKED ISSUE #5529: Fail early on duplicate runtime properties
Currently it's possible that the host (`hostpolicy`) will pass duplicate runtime properties to CoreCLR upon initialization. This can happen if the app/framework specifies some property in its `.runtimeconfig.json` and then `hostpolicy` sets a value for the same property (since it's one of the properties which `hostpolicy` sets).

The current behavior is that the runtime property array will simply have two records for the same property name in this case. CoreCLR will fail with such input. The properties are processed early on in `CorHost2::_CreateAppDomain` https://github.com/dotnet/coreclr/blob/5d57b87227b7fd116735edf9f5f75b3154953d8e/src/vm/corhost.cpp#L705  
This calls into `AppContext.Setup` which will simply iterate over all properties and call `Dictionary.Add` on them: https://github.com/dotnet/coreclr/blob/5d57b87227b7fd116735edf9f5f75b3154953d8e/src/System.Private.CoreLib/src/System/AppContext.CoreCLR.cs#L16  
If there are duplicates the dictionary will throw and exception, which this early in the property leads to runtime initialization failure reported as an HRESULT to `hostpolicy`.

The proposal is to check for duplicates in `hostpolicy` before passing the properties to the runtime. And if there are duplicates fail. This provides a more robust host implementation (doesn't pass invalid data to the runtime) and will allow us to potentially improve this area in the future. For example we may provide ways for the native host to implement some conflict resolution without introducing additional breaking changes.

Technically this is a breaking change as the failure mode would be somewhat different (different output to `stderr`, and different error code returned by `hostpolicy`). But that's the only observable difference, the duplicate properties always lead to a failure.

Note that this change only applies to `hostpolicy` and thus only to .NET Core 3.0, it would not affect down-level versions.

### PR DESCRIPTION
**Pull request by elinor-fung**
Error out before trying to load the runtime when duplicate runtime properties are detected

Resolves #5529

### CODE REVIEW

File: src/corehost/cli/hostpolicy/hostpolicy_context.cpp [hunk 1]
```diff
@@ -146,27 +146,42 @@ int hostpolicy_context_t::initialize(hostpolicy_init_t &hostpolicy_init, const a
...
     // Note: Keep this check outside of the loop above since the _last_ key wins
     // and that could indicate the app paths shouldn't be set.
     if (set_app_paths)
     {
-        coreclr_properties.add(common_property::AppPaths, app_base.c_str());
-        coreclr_properties.add(common_property::AppNIPaths, app_base.c_str());
+        if (!coreclr_properties.add(common_property::AppPaths, app_base.c_str())
+            || !coreclr_properties.add(common_property::AppNIPaths, app_base.c_str()))
+        {
+            trace::error(_X("Duplicate runtime property for app paths"));
```
Comment (vitek-karas) [inline src/corehost/cli/hostpolicy/hostpolicy_context.cpp]: Please include the exact name of the affected properties - it's easier to debug then.
I would also add a single line of explanation, something like: "It's invalid to specify values for properties populated by the hosting layer in the application's .runtimeconfig.json."

File: src/corehost/cli/hostpolicy/hostpolicy_context.cpp [hunk 2]
```diff
@@ -146,27 +146,42 @@ int hostpolicy_context_t::initialize(hostpolicy_init_t &hostpolicy_init, const a
...
     }
 
     // Startup hooks
     pal::string_t startup_hooks;
     if (pal::getenv(_X("DOTNET_STARTUP_HOOKS"), &startup_hooks))
-        coreclr_properties.add(common_property::StartUpHooks, startup_hooks.c_str());
+    {
+        if (!coreclr_properties.add(common_property::StartUpHooks, startup_hooks.c_str()))
+        {
+            trace::error(_X("Duplicate runtime property for startup hooks"));
```
Comment (vitek-karas) [inline src/corehost/cli/hostpolicy/hostpolicy_context.cpp]: Same as above, please include the exact name of the property and the explanation.

File: src/corehost/cli/hostpolicy/coreclr.cpp [hunk 3]
```diff
@@ -212,26 +214,34 @@ coreclr_property_bag_t::coreclr_property_bag_t()
...
-    _values.push_back(value);
+    auto iter = _properties.find(key);
+    if (iter == _properties.cend())
+    {
+        _properties.emplace(key, value);
+        return true;
+    }
+    else
+    {
+        trace::verbose(_X("Overwritting property %s. New value: %s"), key, value);
```
Comment (vitek-karas) [inline src/corehost/cli/hostpolicy/coreclr.cpp]: Nit: trace the old value as well - just in case.
