### PR TITLE
Fix interleaved comhost test logging

### LINKED ISSUE #6355: COM activation tests race in logging
See for example https://dev.azure.com/dnceng/public/_build/results?buildId=181715
The interesting part of the log:
```
  The command output did not contain expected result: "Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 1 of 10""
File Name: D:\a\1\s\bin\tests\win-x64.Release\nativeHosting\0\nativehost.exe
Arguments: comhost concurrent 10 D:\a\1\s\bin\tests\win-x64.Release\0\ComLibrary\bin\ComLibrary.comhost.dll {438968CE-5950-4FBC-90B0-E64691350DF5}
Exit Code: 0
StdOut:
New instance of Server created
New instance of Server created
New instance of Server created
New instance of Server created
Activation of New instance of Server created
{438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 1 of 10
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 2 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 3 of 10
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 4 of 10
New instance of Server created
```

Notice that the expected message is there, but interleaved with another message. It may help to redirect the output/traces to a separate files to avoid races like this in stdout.

### PR DESCRIPTION
**Pull request by elinor-fung**
Fixes #6355

### CODE REVIEW

File: src/corehost/cli/test/nativehost/comhost_test.cpp [hunk 1]
```diff
@@ -109,22 +112,16 @@ bool comhost_test::concurrent(const pal::string_t &comhost_path, const pal::stri
     for (int i = 0; i < count; ++i)
         activations.push_back(std::async(std::launch::async, activate_class, comhost, clsid));
 
+    std::stringstream ss;
     bool succeeded = true;
     for (int i = 0; i < count; ++i)
     {
         HRESULT hr = activations[i].get();
+        log_activation(clsidVect.data(), i + 1, count, hr, ss);
```
Comment (AaronRobinsonMSFT) [inline src/corehost/cli/test/nativehost/comhost_test.cpp]: Doesn't this suffer from the same issues as before except not the the writing could be interleaved in the `stringstream`?

Comment (elinor-fung) [reply src/corehost/cli/test/nativehost/comhost_test.cpp]: The interleaving was between the activated COM class (does a `Console.WriteLine` on instantiation) and the logging here. This change makes it so that the test host stores its messages in the `stringstream` and only prints to stdout at the end (after waiting for all the activations so they would all have printed their output already)
