### PR TITLE
Fix build break by only publishing dotnet-deb-tool for ubuntu.14.04-x64.

### LINKED ISSUE #1570: Only publish dotnet-deb-tool for Ubuntu.14.04-x64 build
See the conversation here:

https://github.com/dotnet/core-setup/pull/1569/files/f2002f2a9eb1755ca5af0adc7e6cac305060590d#r102353639

We currently publish the deb-tool for both x64 and arm builds.  We only need to publish it once.  When we fix this, we can remove `CLI_NUGET_FEED_URL` variable from the Core-Setup-CrossBuild.json pipe build definition.

### PR DESCRIPTION
**Pull request by eerhardt**
Fix #1570

@naamunds @dagood @gkhanna79

### CODE REVIEW

**Comment by eerhardt** [comment]
test Ubuntu arm Release Build

**Comment by eerhardt** [comment]
FYI - I also fixed the package version so it doesn't contain "-beta-beta-001234".  See https://dotnet.myget.org/feed/cli-deps/package/nuget/dotnet-deb-tool.

**Comment by eerhardt** [comment]
test Ubuntu arm Release Build

**Comment by eerhardt** [comment]
@jyoungyun @gkhanna79 - do you know why the Ubuntu arm build is failing?  Is it becuase of #1512?

I'd like to get my change in since the official builds are currently broken.

**Comment by jyoungyun** [comment]
@eerhardt This issue is not related to your patch. This failure issue will be resolved after merging #1572.

File: build_projects/dotnet-host-build/PublishTargets.cs [hunk 1]
```diff
@@ -62,9 +62,13 @@ public static BuildTargetResult Publish(BuildTargetContext c)
         [BuildPlatforms(BuildPlatform.Ubuntu, "14.04")]
```
Comment (dagood) [inline build_projects/dotnet-host-build/PublishTargets.cs]: Can you add `BuildArchitecturesAttribute` rather than doing string matching? Or would the "current" platform still be x64 for the crossbuild, and only the target RID has the needed value?

Comment (eerhardt) [inline build_projects/dotnet-host-build/PublishTargets.cs]: Good call.  It looks like that works.  BuildArchitectures uses this code:

https://github.com/dotnet/core-setup/blob/1dfa45251d6706c046dff384dc81e76161f16440/build_projects/Microsoft.DotNet.Cli.Build.Framework/CurrentArchitecture.cs

Which checks the TARGETPLATFORM environment variable.

We use the same pattern on the GenerateDebs target...

**Comment by eerhardt** [comment]
@dagood - I changed the condition as suggested.

File: build_projects/dotnet-host-build/PublishTargets.cs (hunk 1 above)
Comment (dagood) [inline build_projects/dotnet-host-build/PublishTargets.cs]: Thanks, didn't notice that env var check or see the other usage, makes sense.
